-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5fe82b3a37983b3270b7afa2ed80b90b158f3a7c
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E265,E309,E501']
    -   id: flake8
    -   id: check-yaml
    -   id: debug-statements
