language: python
python:
- '2.7'
env:
- TOXENV=docs
- TOXENV=py27
install:
- pip install tox
script: make test
jobs:
  include:
    - stage: "Elasticsearch"
      env:
        - TOXENV=py27 ES_VERSION=7.0.0-rc1
      install:
        - pip install tox
        - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz
        - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
        - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
      before_script:
        - sleep 10
      script: make test
deploy:
  provider: pypi
  user: yelplabs
  password:
    secure: TpSTlFu89tciZzboIfitHhU5NhAB1L1/rI35eQTXstiqzYg2mweOuip+MPNx9AlX3Swg7MhaFYnSUvRqPljuoLjLD0EQ7BHLVSBFl92ukkAMTeKvM6LbB9HnGOwzmAvTR5coegk8IHiegudODWvnhIj4hp7/0EA+gVX7E55kEAw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Yelp/elastalert
    branch: master
