language: python
python:
- '2.7'
env:
- TOXENV=docs
- TOXENV=py27
install:
- pip install tox
script: make test
jobs:
  include:
    - stage: "Elasticsearch"
      install:
        - pip install tox
        - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
        - mkdir elasticsearch-${ES_VERSION} && tar -xzf elasticsearch-${ES_VERSION}.tar.gz -C elasticsearch-${ES_VERSION} --strip-components=1
        - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
      script:
        - wget -q --waitretry=1 --retry-connrefused --tries=30 -O - http://127.0.0.1:9200
        - make test-elasticsearch
      name: "Elasticsearch 7"
      env: TOXENV=py27 ES_VERSION=7.0.0-rc1-linux-x86_64
    - name: "Elasticsearch 6.6"
      env: TOXENV=py27 ES_VERSION=6.6.2
    - name: "Elasticsearch 6.3"
      env: TOXENV=py27 ES_VERSION=6.3.2
    - name: "Elasticsearch 5.6"
      env: TOXENV=py27 ES_VERSION=5.6.16

deploy:
  provider: pypi
  user: yelplabs
  password:
    secure: TpSTlFu89tciZzboIfitHhU5NhAB1L1/rI35eQTXstiqzYg2mweOuip+MPNx9AlX3Swg7MhaFYnSUvRqPljuoLjLD0EQ7BHLVSBFl92ukkAMTeKvM6LbB9HnGOwzmAvTR5coegk8IHiegudODWvnhIj4hp7/0EA+gVX7E55kEAw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Yelp/elastalert
    branch: master
